# Generated by Django 5.2.5 on 2025-08-12 10:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shift_hours', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('past_week_hours', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.PositiveIntegerField(unique=True)),
                ('distance_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('traffic_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('base_time_min', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inputs', models.JSONField()),
                ('kpis', models.JSONField()),
                ('totals', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True)),
                ('value_rs', models.PositiveIntegerField()),
                ('delivery_time_min', models.PositiveIntegerField(help_text='Planned delivery time in minutes')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateTimeField()),
                ('planned_duration_min', models.PositiveIntegerField()),
                ('on_time', models.BooleanField()),
                ('penalty_rs', models.IntegerField(default=0)),
                ('bonus_rs', models.IntegerField(default=0)),
                ('fuel_cost_rs', models.IntegerField(default=0)),
                ('profit_rs', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.order')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.simulationresult')),
            ],
        ),
    ]
